redis:
  redis-cli: redis-cli -h ${host} -p ${port} -a ${password}

mysql:
  mysql: mysql --protocol=TCP --host=${host} --port=${port} --user=${user} --password=${password} ${name}

mongodb:
  mongo: mongo --host ${host} --port ${port} -u ${user} -p ${password} ${name}

postgresql:
  psql: PGPASSWORD='${password}' psql -h ${host} -p ${port} -d ${name} -U ${user} -w
